### PR TITLE
World Music

### PR DESCRIPTION
**Pull request by zeruth**
General support for world music. All surface map regions have music.

Loads region song information from JSON at server startup.
Remembers unlocked songs and updates music interface with correct colors whenever needed (some ID's still missing)

Plenty of changes still ahead for this PR

### CODE REVIEW

**Comment by lare96** [comment]
Did you want me to merge it now or once you've applied your changes?

**Comment by zeruth** [comment]
Well I still need to do a lot of the changes you requested, so idt it's too necessary to merge unless you want to toy around with it. Caught up in another project atm but i'm not gonna let it rot, I promise

**Comment by zeruth** [comment]
Yeah sorry about this not being done yet. I got caught up in runeliteplus, and idk when I'll get time away from that.

**Comment by lare96** [comment]
I'll merge this into the new branch for now then

**Pull request merged**
